//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantaFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CegAdatok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CegAdatok()
        {
            this.Users = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string Nev { get; set; }
        public int CimID { get; set; }
        public int ElerhetosegekID { get; set; }
        public string AdoSzam { get; set; }
        public string SzamlaSzam { get; set; }
        public string Meghatalmazott { get; set; }
        public Nullable<bool> IsUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
