//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantaFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cimek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cimek()
        {
            this.Feladatoks = new HashSet<Feladatok>();
            this.FeladatokAs = new HashSet<FeladatokA>();
            this.Users = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string Orszag { get; set; }
        public string Varos { get; set; }
        public Nullable<int> PostaKod { get; set; }
        public string Utca { get; set; }
        public string Szam { get; set; }
        public string Egyeb { get; set; }
        public string Megjegyzes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feladatok> Feladatoks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeladatokA> FeladatokAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
