//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantaFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeladatokA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeladatokA()
        {
            this.FelhasznaltAnyagAs = new HashSet<FelhasznaltAnyagA>();
            this.MunkalapokAs = new HashSet<MunkalapokA>();
        }
    
        public int ID { get; set; }
        public string Nev { get; set; }
        public Nullable<int> ProjektAID { get; set; }
        public int FeladatTipusaID { get; set; }
        public string FeladatLeirasa { get; set; }
        public Nullable<System.DateTime> VarhatoKezdes { get; set; }
        public Nullable<System.DateTime> VarhatoBefejezes { get; set; }
        public int ViszonyID { get; set; }
        public Nullable<int> BecsultMunkaOra { get; set; }
        public string MunkaLeirasa { get; set; }
        public Nullable<int> Atiranyitott { get; set; }
        public Nullable<int> FeladatFelelosUserID { get; set; }
        public int CimekID { get; set; }
        public int ElerhetosegekID { get; set; }
        public bool JovahagyvaCB { get; set; }
        public System.TimeSpan Kido { get; set; }
        public Nullable<bool> ArchiveCB { get; set; }
    
        public virtual Cimek Cimek { get; set; }
        public virtual Elerhetosegek Elerhetosegek { get; set; }
        public virtual FeladatTipusok FeladatTipusok { get; set; }
        public virtual ProjektekA ProjektekA { get; set; }
        public virtual User User { get; set; }
        public virtual Viszony Viszony { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FelhasznaltAnyagA> FelhasznaltAnyagAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MunkalapokA> MunkalapokAs { get; set; }
    }
}
