//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantaFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feladat_ElvittEszkoz_ID
    {
        public int ID { get; set; }
        public int FeladatID { get; set; }
        public int ElvittEszkozID { get; set; }
        public Nullable<bool> Modositott { get; set; }
        public Nullable<bool> KiVoltJelolve { get; set; }
    
        public virtual ElvittEszkozok ElvittEszkozok { get; set; }
        public virtual Feladatok Feladatok { get; set; }
    }
}
