//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantaFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feladat_FelhaszAnyag_ID
    {
        public int ID { get; set; }
        public int FeladatID { get; set; }
        public int FelhasznaltAnyagID { get; set; }
    
        public virtual Feladatok Feladatok { get; set; }
        public virtual FelhasznaltAnyagok FelhasznaltAnyagok { get; set; }
    }
}
