//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantaFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FelhasznaltAnyagA
    {
        public int ID { get; set; }
        public string Nev { get; set; }
        public string UserNev { get; set; }
        public int FeladatAID { get; set; }
    
        public virtual FeladatokA FeladatokA { get; set; }
    }
}
