//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantaFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FelhasznaltAnyagok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FelhasznaltAnyagok()
        {
            this.Feladat_FelhaszAnyag_ID = new HashSet<Feladat_FelhaszAnyag_ID>();
        }
    
        public int ID { get; set; }
        public string Nev { get; set; }
        public string UserNev { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feladat_FelhaszAnyag_ID> Feladat_FelhaszAnyag_ID { get; set; }
    }
}
