//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantaFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Koltsegek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Koltsegek()
        {
            this.Munkalap_Koltseg_ID = new HashSet<Munkalap_Koltseg_ID>();
        }
    
        public int ID { get; set; }
        public string KoltsegNeve { get; set; }
        public int KoltsegErteke { get; set; }
        public string KoltsegLeirasa { get; set; }
        public Nullable<int> MunkalapID { get; set; }
    
        public virtual Munkalapok Munkalapok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Munkalap_Koltseg_ID> Munkalap_Koltseg_ID { get; set; }
    }
}
