//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantaFactory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a6b688_sf2025Entities : DbContext
    {
        public db_a6b688_sf2025Entities()
            : base("name=db_a6b688_sf2025Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CegAdatok> CegAdatoks { get; set; }
        public virtual DbSet<Cimek> Cimeks { get; set; }
        public virtual DbSet<Elerhetosegek> Elerhetosegeks { get; set; }
        public virtual DbSet<ElvittEszkozok> ElvittEszkozoks { get; set; }
        public virtual DbSet<Feladat_ElvittEszkoz_ID> Feladat_ElvittEszkoz_ID { get; set; }
        public virtual DbSet<Feladat_FelhaszAnyag_ID> Feladat_FelhaszAnyag_ID { get; set; }
        public virtual DbSet<Feladat_User_ID> Feladat_User_ID { get; set; }
        public virtual DbSet<Feladatok> Feladatoks { get; set; }
        public virtual DbSet<FeladatokA> FeladatokAs { get; set; }
        public virtual DbSet<FeladatTipusok> FeladatTipusoks { get; set; }
        public virtual DbSet<FelhasznaltAnyagA> FelhasznaltAnyagAs { get; set; }
        public virtual DbSet<FelhasznaltAnyagok> FelhasznaltAnyagoks { get; set; }
        public virtual DbSet<Jogosultsag> Jogosultsags { get; set; }
        public virtual DbSet<Koltsegek> Koltsegeks { get; set; }
        public virtual DbSet<Munkalap_Koltseg_ID> Munkalap_Koltseg_ID { get; set; }
        public virtual DbSet<Munkalapok> Munkalapoks { get; set; }
        public virtual DbSet<MunkalapokA> MunkalapokAs { get; set; }
        public virtual DbSet<Projektek> Projekteks { get; set; }
        public virtual DbSet<ProjektekA> ProjektekAs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Viszony> Viszonies { get; set; }
    }
}
