//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantaFactory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a6b688_sf2025Entities : DbContext
    {
        public db_a6b688_sf2025Entities()
            : base("name=db_a6b688_sf2025Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CegAdatok> CegAdatok { get; set; }
        public virtual DbSet<Cimek> Cimek { get; set; }
        public virtual DbSet<Elerhetosegek> Elerhetosegek { get; set; }
        public virtual DbSet<ElvittEszkozok> ElvittEszkozok { get; set; }
        public virtual DbSet<Feladat_ElvittEszkoz_ID> Feladat_ElvittEszkoz_ID { get; set; }
        public virtual DbSet<Feladat_FelhaszAnyag_ID> Feladat_FelhaszAnyag_ID { get; set; }
        public virtual DbSet<Feladat_User_ID> Feladat_User_ID { get; set; }
        public virtual DbSet<Feladatok> Feladatok { get; set; }
        public virtual DbSet<FeladatokA> FeladatokA { get; set; }
        public virtual DbSet<FeladatTipusok> FeladatTipusok { get; set; }
        public virtual DbSet<FelhasznaltAnyagA> FelhasznaltAnyagA { get; set; }
        public virtual DbSet<FelhasznaltAnyagok> FelhasznaltAnyagok { get; set; }
        public virtual DbSet<Jogosultsag> Jogosultsag { get; set; }
        public virtual DbSet<Koltsegek> Koltsegek { get; set; }
        public virtual DbSet<Munkalap_Koltseg_ID> Munkalap_Koltseg_ID { get; set; }
        public virtual DbSet<Munkalapok> Munkalapok { get; set; }
        public virtual DbSet<MunkalapokA> MunkalapokA { get; set; }
        public virtual DbSet<Projektek> Projektek { get; set; }
        public virtual DbSet<ProjektekA> ProjektekA { get; set; }
        public virtual DbSet<sysdiagram> sysdiagram { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Viszony> Viszony { get; set; }
    }
}
