//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantaFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MunkalapokA
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Datum { get; set; }
        public string Magyjegyzes { get; set; }
        public Nullable<int> Atiranyitott { get; set; }
        public bool JovahagyvaCB { get; set; }
        public int FeladatAID { get; set; }
        public System.DateTime MunkaDatuma { get; set; }
        public Nullable<decimal> MunkaOra { get; set; }
        public Nullable<int> MegtettKM { get; set; }
        public bool Megtekintve { get; set; }
        public System.TimeSpan KIdo { get; set; }
        public System.TimeSpan BIdo { get; set; }
        public Nullable<bool> ArchiveCB { get; set; }
    
        public virtual FeladatokA FeladatokA { get; set; }
        public virtual User User { get; set; }
    }
}
