//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantaFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Munkalapok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Munkalapok()
        {
            this.Koltsegeks = new HashSet<Koltsegek>();
            this.Munkalap_Koltseg_ID = new HashSet<Munkalap_Koltseg_ID>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Datum { get; set; }
        public string Magyjegyzes { get; set; }
        public Nullable<int> Atiranyitott { get; set; }
        public bool JovahagyvaCB { get; set; }
        public int FeladatID { get; set; }
        public System.DateTime MunkaDatuma { get; set; }
        public Nullable<decimal> MunkaOra { get; set; }
        public Nullable<int> MegtettKM { get; set; }
        public bool Megtekintve { get; set; }
        public System.TimeSpan KIdo { get; set; }
        public System.TimeSpan BIdo { get; set; }
        public Nullable<bool> ArchiveCB { get; set; }
    
        public virtual Feladatok Feladatok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Koltsegek> Koltsegeks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Munkalap_Koltseg_ID> Munkalap_Koltseg_ID { get; set; }
        public virtual Users User { get; set; }
    }
}
