//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantaFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjektekA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjektekA()
        {
            this.FeladatokAs = new HashSet<FeladatokA>();
        }
    
        public int ID { get; set; }
        public string Nev { get; set; }
        public string AzonositoKod { get; set; }
        public Nullable<bool> ArchiveCB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeladatokA> FeladatokAs { get; set; }
    }
}
