//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantaFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Feladat_User_ID = new HashSet<Feladat_User_ID>();
            this.Feladatoks = new HashSet<Feladatok>();
            this.Feladatoks1 = new HashSet<Feladatok>();
            this.FeladatokAs = new HashSet<FeladatokA>();
            this.Munkalapoks = new HashSet<Munkalapok>();
            this.MunkalapokAs = new HashSet<MunkalapokA>();
        }
    
        public int UserID { get; set; }
        public string VezetekNev { get; set; }
        public string KeresztNev { get; set; }
        public int ElerhetosegekID { get; set; }
        public int CimekID { get; set; }
        public int JogosultsagID { get; set; }
        public int ViszonyID { get; set; }
        public string Jelszo { get; set; }
        public System.DateTime SzuletesiDatum { get; set; }
        public string SzuletesiHely { get; set; }
        public string AnyjaNeve { get; set; }
        public string SzemIgSzam { get; set; }
        public string SzamlaSzam { get; set; }
        public string AdoSzam { get; set; }
        public Nullable<int> CegAdatokID { get; set; }
        public bool Megegyezik { get; set; }
        public string GKRendszam { get; set; }
        public Nullable<int> UzemanyagAr { get; set; }
        public Nullable<int> Berezes { get; set; }
        public string ErtSzemelyNeve { get; set; }
        public Nullable<int> ErtSzemelyElerhetosegID { get; set; }
        public bool EmailMegerositve { get; set; }
        public System.Guid AktivaloKod { get; set; }
        public string JelszoModositoKod { get; set; }
        public Nullable<bool> BejelentkezveMarad { get; set; }
        public bool GDPR { get; set; }
    
        public virtual CegAdatok CegAdatok { get; set; }
        public virtual Cimek Cimek { get; set; }
        public virtual Elerhetosegek Elerhetosegek { get; set; }
        public virtual Elerhetosegek Elerhetosegek1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feladat_User_ID> Feladat_User_ID { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feladatok> Feladatoks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feladatok> Feladatoks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeladatokA> FeladatokAs { get; set; }
        public virtual Jogosultsag Jogosultsag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Munkalapok> Munkalapoks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MunkalapokA> MunkalapokAs { get; set; }
        public virtual Viszony Viszony { get; set; }
    }
}
